spring:
  application:
    name: DbQuerzApp
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate   # or update for dev
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: never
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG