CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       first_name VARCHAR(255) NOT NULL,
                       last_name  VARCHAR(255) NOT NULL,
                       age INT NOT NULL CHECK (age >= 0),
                       email VARCHAR(255) NOT NULL UNIQUE,
                       phone VARCHAR(20),
                       address VARCHAR(255)
);